### ISSUE TITLE
"Too many open files"

### ISSUE THREAD

**Issue by yodsv2** [input-output-hk/jormungandr#979] opened 2019-10-18 02:29 UTC
**Describe the bug**

**Mandatory Information**
1.  jcli 0.6.1 (master-a0de8d47, release, macos [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
2. jormungandr 0.6.1 (master-4e8cd69e, release, macos [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

**To Reproduce**
1. Launch Jormungandr on OSX Catalina 
2. wait till error appears

Oct 17 19:05:24.099 ERRO Error while accepting connection on 0.0.0.0:3100: Os { code: 24, kind: Other, message: "Too many open files" }, task: network
thread 'network0' panicked at 'Box<Any>', jormungandr/src/main.rs:225:30

stack backtrace:
   0:        0x10cee0c52 - std::panicking::default_hook::{{closure}}::h3f994bbc901f9889
   1:        0x10cee091d - std::panicking::default_hook::h6c261b7dad1af707
   2:        0x10cee1390 - std::panicking::rust_panic_with_hook::hd3c20890ac648923
   3:        0x10cf1cf81 - std::panicking::begin_panic::h5370d9343a8bf397
   4:        0x10c6f8750 - jormungandr::start_services::{{closure}}::{{closure}}::h16040071a7e3ef96
   5:        0x10c751c82 - std::panicking::try::do_call::h16fe170ee25e8a9a
   6:        0x10cee4c1f - __rust_maybe_catch_panic
   7:        0x10c6ee065 - <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll::h2aa3dceffb623433
   8:        0x10c6e82f8 - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h67b9e1bd7f4099dc
   9:        0x10cec01fd - futures::task_impl::std::set::he4abe935f2c247b4
  10:        0x10cebfcf6 - std::panicking::try::do_call::hd5de3c5276abaa28
  11:        0x10cee4c1f - __rust_maybe_catch_panic
  12:        0x10cebf92c - tokio_threadpool::task::Task::run::h52cf13adc2151da5
  13:        0x10ceba552 - tokio_threadpool::worker::Worker::run_task::h93ac6c1c576227c2
  14:        0x10ceb99fb - tokio_threadpool::worker::Worker::run::h405b20cd460cd71f
  15:        0x10ce9c82d - std::thread::local::LocalKey<T>::with::h29197d21e620d4dd
  16:        0x10ce9cbd3 - std::thread::local::LocalKey<T>::with::h744057590b2725b9
  17:        0x10ce9ca85 - std::thread::local::LocalKey<T>::with::h6dbfe345bda05cf6
  18:        0x10ce9f081 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h8083bd491ab6743c
  19:        0x10cebcdbb - std::thread::local::LocalKey<T>::with::h6415e68e51419bd6
  20:        0x10cebcbbb - std::thread::local::LocalKey<T>::with::h4289c37325305088
  21:        0x10ceb64f0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h32e3a6b82f92e799
  22:        0x10cebfc60 - std::panicking::try::do_call::h22b7af7a5c6f90e6
  23:        0x10cee4c1f - __rust_maybe_catch_panic
  24:        0x10ceb7e37 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h04fef61c01658154
  25:        0x10ced1f7e - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h04257f365502db2d
  26:        0x10cee413e - std::sys::unix::thread::Thread::new::thread_start::haec1a494f7a7ae67
  27:     0x7fff68402cde - _pthread_start

Full terminal output below.
[Terminal_output.txt](https://github.com/input-output-hk/jormungandr/files/3742062/Terminal_output.txt)

**Comment by mzabaluev** [comment] 2019-10-18 07:12
Looks like a duplicate of #923

**Closed by mzabaluev** 2019-10-18 07:12 UTC
Labels: duplicate
