### ISSUE TITLE
Error returned from jcli account get function

### ISSUE THREAD

**Issue by carlwhiston** [input-output-hk/jormungandr#974] opened 2019-10-17 08:53 UTC
**Describe the bug**

**Mandatory Information**
1. `jcli --0.6.1` stderr;
2. `jormungandr --0.6.1` stderr;

Hey guys. Successfully received funds from the faucet but cant get the ballance. Below command returns Error on Unix box. Any ideas? Anybody got a working command to check the ballance of an account? Thanks. Carl

Steps
-----
1) Created new account
2) Successfully put money into account with a Faucet request
3) Went to confirm my new balance with the below command which fails

./jcli rest v0 account get ca1s4cx0uqvl96rnst5u9cw7yzj62vzf9ulj09pwxmqpg9dvvt7kmnw6k55qy9 --host "http://127.0.0.1:3101/api"

Returns below error

failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://127.0.0.1:3101/api/v0/account/7067f00cf97439c174e170ef1052d29824979f93ca171b600a0ad6317eb6e6ed: Client Error: 404 Not Found

**Comment by carlwhiston** [comment] 2019-10-17 08:55
ps. Lots of people on the telenet stake pool best practice work group have the same problem

**Comment by smurf123444** [comment] 2019-10-20 08:21
You can make a Bash file in windows to run in git bash with this code.

`#!/bin/sh

# Disclaimer:
#
#  The following use of shell script is for demonstration and understanding
#  only, it should *NOT* be used at scale or for any sort of serious
#  deployment, and is solely used for learning how the node and blockchain
#  works, and how to interact with everything.
#
#  It also asumes that `jcli` is in the same folder with the script.
#
#  Tutorials can be found here: https://github.com/input-output-hk/shelley-testnet/wiki

### CONFIGURATION
CLI="./jcli"
COLORS=1
ADDRTYPE="--testing"


ACCOUNT_ADDR="$1"
REST_PORT="$2"

REST_URL="http://127.0.0.1:${REST_PORT}/api"



$CLI rest v0 account get ${ACCOUNT_ADDR} -h ${REST_URL}

exit 0`

Just use your address and port as arguments. no instruction manual though 💯

**Comment by smurf123444** [comment] 2019-10-21 01:24
@rdlrt stop with the negative emojis you f-ing noob

**Comment by vincenthz** [comment] 2019-10-21 04:26
@smurf123444 please keep it civil, no point insulting anyone. I'm not a fan of negative emojis either, but you can just ignore them.

**Comment by Linicks** [comment] 2019-11-01 20:10
**I'm also having difficulty with this, using the script mentioned above and entering the command manually.**  I used this process to create my address(https://iohk.zendesk.com/hc/en-us/articles/360036923453), and the shelly testnet faucet had no issue sending the ada.

###########################
jormungandr 0.7.0-rc3 (HEAD-466c0fb, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
###########################
failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://ip-address:3101/api/v0/account/1838407cfbce0eead918418c12f243ec5565e49b35f88b38c509b34784ef83f5: Client Error: 404 Not Found
###########################

**Comment by CodeSandwich** [comment] 2019-11-13 14:40
I'm quite sure that this is not a bug. We have exactly this scenario in automatic tests (`jormungandr-integration-tests::jcli::transaction::e2e::test_account_is_created_if_transaction_out_is_account`) and it's working reliably. 

@carlwhiston Was the transaction that was supposed to create an account included in the block? When it's only pending and not in the block yet, the account isn't considered existing by the node. The script probably executed in milliseconds and didn't give the node time to build a fresh block.

@smurf123444 @Linicks The script only creates a random number, it has no meaning unless it's used in a transaction accepted by node. It's like writing down an address of a home, that may or may not be built in the future. Sure, everybody will tell you that the address has valid format, but nobody has ever heard about a house standing there, you have to build it first.

Please let me know if the issue really exists, if no, I want to close it.

**Comment by carlwhiston** [comment] 2019-11-13 15:12
HI.  You can close now as node may not of brental in sync. After the
snapshot I won't need a faucet so that's fine to close this now. Thanks.
Carl

**Comment by smurf123444** [comment] 2019-11-13 15:38
I believe it is fixed as well. Thanks!

**Closed** 2019-11-13 18:05 UTC
