### ISSUE TITLE
404 Not Found status code is too generic for unused addresses which confuses jcli users

### ISSUE THREAD

**Issue by mark-stopka** [input-output-hk/jormungandr#1361] opened 2019-12-13 17:10 UTC
**Is your feature request related to a problem/context ? Please describe if applicable.**
It's confusing for many users when querying an unused address that they get 404 Not Found error.

**Describe the solution you'd like**
It would be beneficial if the REST API would validate the address and if address is valid return some other (perhaps custom) status code with a message "This address does not have and never had any balance" or something along those lines... 

**Additional context**
Questions related to this generic 404 Not Found have been repeatedly raised within Cardano Stake Pool Workgroup Telegram channel.

**Comment by eugene-babichenko** [comment] 2019-12-13 20:20
Duplicate of #1360

**Closed by eugene-babichenko** 2019-12-13 20:20 UTC
