### ISSUE TITLE
Leadership manager in invalid state from block drifting

### ISSUE THREAD

**Issue by johnalotoski** [input-output-hk/jormungandr#813] opened 2019-09-23 22:55 UTC
Coredumps/Panic related to tokio-runtime-worker are observed shortly after starting a node. Journalctl snippet and coredump backtrace attached.

jcli 0.5.0 (, release, linux [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
jormungandr 0.5.0 (, release, linux [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]

Coredump/Journalctl logs:
[coredump-r-b-2.zip](https://github.com/input-output-hk/jormungandr/files/3644450/coredump-r-b-2.zip)

May be related to #803

**Comment by NicolasDP** [comment] 2019-09-24 07:15
Not related to #803

**Comment by NicolasDP** [comment] 2019-09-24 07:32
what the configuration file for this?

**Comment by mzabaluev** [comment] 2019-09-24 07:38
Please also attach the node's configuration file.
The log file starts at the panic dump. Can you post the excerpt preceding it, if there was any?

**Comment by johnalotoski** [comment] 2019-09-24 13:16
Hi @NicolasDP, @mzabaluev, yes, please see the attached addition journalctl log and sanitized config file in the following zip.  Thanks.
[journalctl-log-jormungandr2.zip](https://github.com/input-output-hk/jormungandr/files/3647350/journalctl-log-jormungandr2.zip)

**Comment by johnalotoski** [comment] 2019-09-24 13:42
The config file above shows debug for the logging, but it was default (info, I believe) at the time when the coredump occurred.

**Comment by mzabaluev** [comment] 2019-09-25 05:52
Thank you @johnalotoski .
Looks like there is an invalid block in storage and it hits an unwrap [in chain-storage-sqlite](https://github.com/input-output-hk/chain-libs/blob/6e842963ac1546173005736712f3cfcb5f7243e4/chain-storage-sqlite/src/lib.rs#L137)

**Comment by dkijania** [comment] 2019-09-25 10:08
duplicate of #815

**Comment by johnalotoski** [comment] 2019-09-25 12:54
Thank you @dkijania.  Would the invalid block followed by panic on unwrap you mention above also match the following error that I've received multiple times on another cluster without rust backtrace on and no coredump seen yet (I'm repeating the cluster with backtrace enabled to get some more info):

```
10989 Sep 25 03:14:38.013 INFO block from leader event successfully stored, date: 30956.32, parent: 0b21183b6181efdd08596bf0846afab87c5ba511dbc1f3aeebafc0058f3cd531, hash: 6116bdf9528a42178      b22c6b27510b324f63f1fe83b06d222acf1d5db5af88a3b, task: block
10990 Sep 25 03:15:06.014 INFO leader event starting, date: 30956.46, leader: 1, task: leadership
10991 thread 'block0' panicked at 'called `Result::unwrap()` on an `Err` value: Error(CannotApplyBlock, State { next_error: Some(NonMonotonicDate { block_date: BlockDate { epoch: 30956, slo      t_id: 46 }, chain_date: BlockDate { epoch: 30956, slot_id: 46 } }), backtrace: InternalBacktrace { backtrace: None } })', src/libcore/result.rs:999:5
10992 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
10993 Sep 25 03:15:06.020 ERRO failed to send block announcement to the block task, sub_task: server, task: network
10994 thread 'leadership0' panicked at 'Expect the event to not close', src/libcore/option.rs:1034:5
10995 Sep 25 03:15:06.021 ERRO failed to send block announcement to the block task, sub_task: server, task: network
10996 thread 'tokio-runtime-worker-4' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError("...")', src/libcore/result.rs:999:5
10997 Sep 25 03:15:06.023 ERRO failed to send block announcement to the block task, sub_task: server, task: network
10998 Sep 25 03:15:06.023 ERRO failed to send block announcement to the block task, sub_task: server, task: network
10999 Sep 25 03:15:06.024 ERRO failed to send block announcement to the block task, sub_task: server, task: network
11000 Sep 25 03:15:06.025 ERRO failed to send block announcement to the block task, sub_task: server, task: network
11001 thread 'tokio-runtime-worker-5' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError("...")', src/libcore/result.rs:999:5
11002 thread 'tokio-runtime-worker-1' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError("...")', src/libcore/result.rs:999:5
11003 Sep 25 03:15:08.027 ERRO failed to send block announcement to the block task, sub_task: server, task: network
11004 thread 'tokio-runtime-worker-1' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError("...")', src/libcore/result.rs:999:5
11005 Sep 25 03:15:08.028 INFO incoming P2P connection on 127.0.0.1:4005, peer_addr: 127.0.0.1:53666, task: network
```

**Comment by dkijania** [comment] 2019-10-01 11:20
@johnalotoski This issue is also connected to this one #855

**Comment by NicolasDP** [comment] 2019-10-04 09:42
This is duplicate of #855 the first error has been fixed in (the one commented in the issue description's logs). the last comment is definitely #855

**Closed by NicolasDP** 2019-10-04 09:42 UTC
Labels: Priority - High, bug, duplicate, question, subsys-network
