### ISSUE TITLE
Getting error in Mac - ERRO cannot process network headers, reason: deadline has elapsed, task: block

### ISSUE THREAD

**Issue by BitcoinMicroPaymentNetwork** [input-output-hk/jormungandr#1455] opened 2019-12-26 09:35 UTC
**Describe the bug**
Dec 26 14:56:39.924 ERRO cannot process network headers, reason: deadline has elapsed, task: block

**Mandatory Information**
1. jcli 0.8.5 (HEAD-3db0680, release, macos [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2. jormungandr 0.8.5 (HEAD-3db0680, release, macos [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
After running node for an hour in mac it happes

**Comment by rinor** [comment] 2020-01-03 12:33
Can we close this one in favor of https://github.com/input-output-hk/jormungandr/issues/1413 since there is more information there and the issue is the same. Thank you,

**Comment by rinor** [comment] 2020-01-06 12:49
@BitcoinMicroPaymentNetwork closing this one in favor of https://github.com/input-output-hk/jormungandr/issues/1413.

**Closed by rinor** 2020-01-06 12:49 UTC
Labels: duplicate
