### ISSUE TITLE
Node terminated with error 

### ISSUE THREAD

**Issue by BitcoinMicroPaymentNetwork** [input-output-hk/jormungandr#1442] opened 2019-12-25 03:33 UTC
**Describe the bug**
Node terminated after receiving garbage 

Dec 25 00:51:54.563 INFO connecting to peer, node_id: d91ef2ed737f4ada7c648265d16478414f1eaa6fd2108cff, peer_addr: 85.25.159.219:3000, task: network
Dec 25 00:51:54.572 ERRO Error while accepting connection on 0.0.0.0:3000: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, task: network
Dec 25 00:51:54.573 WARN response canceled by the processing task, request: UploadBlocks, sub_task: server, task: network
Dec 25 00:51:54.573 WARN response canceled by the processing task, request: UploadBlocks, sub_task: server, task: network
Dec 25 00:51:54.575 INFO service finished with error, task: network
Dec 25 00:51:54.576 CRIT Service has terminated with an error
A service has terminated with an error
Rohits-MacBook-Pro:jormungandr-v0.8.5-x86_64-apple-darwin rohitchandan$ 

**Mandatory Information**
1. jcli 0.8.5-alpha1 (HEAD-5d28516, release, macos [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2.   `jormungandr jormungandr 0.8.5-alpha1 (HEAD-5d28516, release, macos [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
1. received garbage  and node shutdown with above log

**Comment by eugene-babichenko** [comment] 2019-12-27 16:40
Duplicate of #1401

**Closed** 2020-01-08 08:50 UTC
Labels: duplicate
