### ISSUE TITLE
Missed the deadline to compute the schedule

### ISSUE THREAD

**Issue by BitcoinMicroPaymentNetwork** [input-output-hk/jormungandr#1601] opened 2020-01-19 16:08 UTC
**Describe the bug**
Log below
Jan 19 21:19:07.482 ERRO Eek... Too late, we missed an event schedule, system time might be off?, event_end: 2020-01-19T15:49:07+00:00, event_start: 2020-01-19T15:49:05+00:00, event_date: 36.37064, leader_id: 1, task: leadership

Jcli query below 
Rohits-MacBook-Pro:rohitchandan$ jcli rest v0 leaders logs get -h http://127.0.0.1:3100/api
 created_at_time: "2020-01-18T19:13:49.422786+00:00"
  enclave_leader_id: 1
  finished_at_time: ~
  scheduled_at_date: "36.37064"
  scheduled_at_time: "2020-01-19T15:49:05+00:00"
  status: Pending
  wake_at_time: ~
Rohits-MacBook-Pro:rohitchandan$ jcli rest v0 leaders logs get -h http://127.0.0.1:3100/api
created_at_time: "2020-01-18T19:13:49.422786+00:00"
  enclave_leader_id: 1
  finished_at_time: "2020-01-19T15:49:07.483840+00:00"
  scheduled_at_date: "36.37064"
  scheduled_at_time: "2020-01-19T15:49:05+00:00"
  status:
    Rejected:
      reason: Missed the deadline to compute the schedule
  wake_at_time: "2020-01-19T15:49:07.482823+00:00"

**Mandatory Information**
Jormungandr version 0.8.6

**Comment by rdlrt** [comment] 2020-01-19 20:37
Duplicate of (and already referred in) #1580

**Comment by rinor** [comment] 2020-01-30 17:34
@BitcoinMicroPaymentNetwork closing this one so we can track all the communications on the other one. As for the reason this happens, one of the possible causes is related to those high cpu usage/spikes that causes the timer to fire/executed late. Thanks for the report.

**Closed by rinor** 2020-01-30 17:34 UTC
Labels: duplicate
