### ISSUE TITLE
Peer GCed causing node to time out rest api

### ISSUE THREAD

**Issue by Willburn** [input-output-hk/jormungandr#1634] opened 2020-01-23 17:58 UTC
**Describe the bug**
0.8.7 caused several of my nodes to hang the rest api in "timed out" and reserving most of system memory over time. Putting logging to warning levels shows peer gced messages when the behavior of timing out rest api starts to happen. 

**To Reproduce**
Sadly it is unclear why this happened to some of my nodes and not to others.

**Expected behavior**
I expected the rest api to not hang. Journactl shows the node as still active as it outputs warning messages but I cannot check jorumgandr stats of the node due to the rest api timing out.

**Comment by mzabaluev** [comment] 2020-01-23 19:38
Duplicate of #1626

**Closed by mzabaluev** 2020-01-23 19:38 UTC
Labels: duplicate
