### ISSUE TITLE
0.7.1 - Error processing ChainHeader handling

### ISSUE THREAD

**Issue by feqifei** [input-output-hk/jormungandr#1179] opened 2019-11-22 15:33 UTC
**Describe the bug**
Switching the node from 0.7.0 to 0.7.1 and keeping the same blocks.sqlite file I faced this error several times. After a while (40mins to 1h and 20mins) the node crashes with the error mentioned in the title. I didn't face it anymore after I made a fresh restart of the node without the blocks.sqlite db generated by the previous jormungandr version and then I moved back the db restarting the node again.

**Mandatory Information**
1. jcli 0.7.1 (HEAD-c57466d, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
2. jormungandr 0.7.1 (HEAD-c57466d, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

As attachment the full log that contains three error events, the last one with details generated by RUST_BACKTRACE=full.

[nohup.txt](https://github.com/input-output-hk/jormungandr/files/3880208/nohup.txt)

**Comment by liebmann** [comment] 2019-11-23 12:12
I can confirm the ChainHeader bug. With a blockchain stored in memory the bug appears within a minute or two. See the log below.

`./jormungandr --genesis-block-hash dceef4d6696ead83eadb5104c6383e1905aa81fc7a79ea2ca87a97c2bfd2f4a1 --config config.yaml --secret node_secret.yaml`
`Nov 23 11:36:51.728 INFO Starting jormungandr 0.7.1 (HEAD-c57466d, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)], task: init`
`Nov 23 11:36:51.734 INFO storing blockchain in memory, task: init`
`...`
`Nov 23 11:37:45.107 ERRO Cannot process block event, reason: Error processing ChainHeader handling, task: block`
`Nov 23 11:37:45.109 INFO Shutting down node`
`Nov 23 11:37:45.110 WARN Shutting down service client-query (up since 46s 39ms 298us 526ns): receiving on a closed channel, task: client-query`

**Comment by bjarnekvae** [comment] 2019-11-25 13:31
Happened to me as well, here are a strace log
[chainHeader.zip](https://github.com/input-output-hk/jormungandr/files/3886817/chainHeader.zip)

**Comment by NicolasDP** [comment] 2019-11-27 11:13
Hmm thanks. It seems to be the network should not fail on that error. If the error happen, it is okay to log it. but It should not mean the node should stop. This can be an error with the remote node.

@mzabaluev can you look into this?

**Comment by liebmann** [comment] 2019-11-28 17:27
@NicolasDP Looks like the ChainHeader error is fixed now in v0.7.5.

**Comment by NicolasDP** [comment] 2019-12-06 09:19
I believe this is fixed with #1290 and #1292 . It will be included in the next release

**Closed by NicolasDP** 2019-12-06 09:19 UTC
Labels: subsys-network
