### ISSUE TITLE
Jormungandr v0.6.5 thread 'block0' panicked

### ISSUE THREAD

**Issue by psychomb** [input-output-hk/jormungandr#996] opened 2019-10-19 12:00 UTC
**Describe the bug**
The node crashes after a while

**Mandatory Information**
1. jcli 0.6.5 (HEAD-052f7be7, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
2. jormungandr 0.6.5 (HEAD-052f7be7, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

**To Reproduce**
1. Cargo install v0.6.5
2. RUST_BACKTRACE=full jormungandr --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --config config.yaml --secret pool-secret.yaml
3. Wait a bit
4. See it crash

**Expected behavior**
No crash :)

**log**
[log_full.txt](https://github.com/input-output-hk/jormungandr/files/3746619/log_full.txt)

**Comment by NicolasDP** [comment] 2019-10-21 06:09
Duplicate of #788

**Closed by NicolasDP** 2019-10-21 06:09 UTC
