### ISSUE TITLE
DatabaseBusy - sqllite db locked (0.7.0)

### ISSUE THREAD

**Issue by mikewday** [input-output-hk/jormungandr#1148] opened 2019-11-18 12:55 UTC
**Describe the bug**

sqllite database locked error. 

jcli 0.7.0 (HEAD-a93d4f67, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

jormungandr 0.7.0 (HEAD-a93d4f67, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**
Running as a stakepool
./jormungandr --config node-config.yaml --secret node_secret.yaml --genesis-block-hash 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29

After approximately 6 hours running, I received the following error and jormungandr stopped functioning. Backtrace was not enabled (everything had been very stable).
I was away from this node for 2 days but, when restarted, jormungandr fired back up with no issues/errors (without deleting the database, etc.). Only one instance of jormungandr was running on my hardware.
The most recent change made before this behavior occurred was setting up a pool and restarting with node_secret. 

node stats were being run every 5 minutes from jcli
No "external" program had any connection to the sqllite db. 

-------------------------------------------------------------------------------------------
Nov 16 00:03:31.563 INFO received block announcement, hash: dcb7be36a3a1b81cf814a6d7291b5846097dcfa9a374412812d581571b614494, direction: in, stream: block_events, node_id: 2cbdc9dbd3adb59aa2908e37e3cb8e204cacb827c115f037, peer_addr: 52.221.142.167:3100, task: network
Nov 16 00:05:10.760 INFO received block announcement, hash: 0ab9084d8560d929dfa63e2d13b1452d899ae68651c94bc9b08edecdba38198b, direction: in, stream: block_events, node_id: 3b0397a2eca46cf5438d0318aa052d125b45632142ecea0b, peer_addrthread ': block0' panicked at 'called Result::unwrap() on an Err value: Error(Msg("cannot process block announcement"), State { next_error: Some(Error(Msg("cannot check if the block is in the storage"), State { next_error: Some(BackendError(SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked")))), backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })', src\libcore\result.rs:1165:5
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace.
40.118.186.37:5222, task: network
Nov 16 00:05:37.599 INFO received block announcement, hash: 0ab9084d8560d929dfa63e2d13b1452d899ae68651c94bc9b08edecdba38198b, direction: in, stream: block_eventscalled Result::unwrap() on an Err value: Error(Msg("cannot process block announcement"), State { next_error: Some(Error(Msg("cannot check if the block is in the storage"), State { next_error: Some(BackendError(SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked")))), backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })
, node_id: 039e217384e526530c04c353d065a38d105e453491a11427, peer_addr: 52.8.14.1:3000, task: network
Nov 16 00:05:45.180 INFO received block announcement, hash: 0ab9084d8560d929dfa63e2d13b1452d899ae68651c94bc9b08edecdba38198b, direction:
-------------------------------------------------------------------------------------------

**Expected behavior**
avoid db locking conflicts and/or error handle

**Additional context**

**Comment by mzabaluev** [comment] 2019-12-03 11:11
Error handling has seen some improvements in the run-up to 0.8.0. Please test with the latest RC release. The SQLite locking error is the root cause here, though.

**Comment by mzabaluev** [comment] 2020-02-07 12:35
The database has been reworked and a similar problem fixed in #1641.

**Closed by mzabaluev** 2020-02-07 12:35 UTC
Labels: bug, subsys-storage
