### ISSUE TITLE
When it seems like the node is hanging, it would be nice to know what is happening and seeing progress.

### ISSUE THREAD

**Issue by smenroll** [input-output-hk/jormungandr#907] opened 2019-10-08 02:39 UTC
There are at least two scenario where it normally takes 10-30mins. until something happens.
1. The first time the node starts up, there is a wait for a download. It would be an amazing user experience if the node gave feedback on the download progress, so that users don't think there is anything wrong. This will also lower the trouble tickets / issues for the support team. So by helping your users, you will be helping your self.

2. After this first download is done, there is a second wait when connecting to connecting to initial gossip peers. Here I was told, I just had to leave the node for up to 30mins. This is an extremely long wait without giving the users some feedback of what is going on and some progress.

These two feedback loops to node admins would greatly improve the experience.
Thanks for reading and considering this!

**Comment by psychomb** [comment] 2019-10-08 12:00
for the first issue you're mentionning, the is quite close to issues #857

**Comment by NicolasDP** [comment] 2019-10-15 08:20
I think this is an overall duplicate of #857 I have added a comment to guide the dev on how to address this and provide more useful feedback.

The delays of 30min describe in `2.` was an unfortunate issue related to #860 which we believe has been near fully addressed since the release `0.6.0`.

**Closed by NicolasDP** 2019-10-15 08:20 UTC
