### ISSUE TITLE
Node Crash on Ubuntu 18.04

### ISSUE THREAD

**Issue by Proxiweb** [input-output-hk/jormungandr#954] opened 2019-10-15 09:32 UTC
{"msg":"error connecting to peer","level":"INFO","ts":"2019-10-15T11:25:12.172466288+02:00","peer_addr":"3.115.194.22:3000","task":"network","reason":"Connection refused (os error 111)"}
{"msg":"leader event starting","level":"INFO","ts":"2019-10-15T11:25:16.002230212+02:00","date":"235.2751","leader":"1","task":"leadership"}
thread 'block0' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Msg("cannot process leadership block"), State { next_error: Some(Error(BlockHeaderVerificationFailed("Invalid block message"), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0: error_chain::backtrace::imp::InternalBacktrace::new
   1: <error_chain::State as core::default::Default>::default
   2: jormungandr::blockchain::chain::Blockchain::post_check_header
   3: futures::future::chain::Chain<A,B,C>::poll
   4: futures::future::chain::Chain<A,B,C>::poll
   5: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
   6: <futures::future::map::Map<A,F> as futures::future::Future>::poll
   7: futures::task_impl::std::set
   8: std::thread::local::LocalKey<T>::with
   9: futures::future::Future::wait
  10: jormungandr::blockchain::process::run_handle_input
  11: jormungandr::blockchain::process::handle_input
  12: futures::future::catch_unwind::<impl futures::future::Future for std::panic::AssertUnwindSafe<F>>::poll
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  15: <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll
  16: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  17: futures::task_impl::std::set
  18: std::panicking::try::do_call
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  20: tokio_threadpool::task::Task::run
  21: tokio_threadpool::worker::Worker::run_task
  22: tokio_threadpool::worker::Worker::run
  23: std::thread::local::LocalKey<T>::with
  24: std::thread::local::LocalKey<T>::with
  25: std::thread::local::LocalKey<T>::with
  26: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  27: std::thread::local::LocalKey<T>::with
  28: std::thread::local::LocalKey<T>::with
  29: std::sys_common::backtrace::__rust_begin_short_backtrace
  30: std::panicking::try::do_call
  31: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  32: core::ops::function::FnOnce::call_once{{vtable.shim}}
  33: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  34: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  35: start_thread
  36: __clone
) } })), backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0: error_chain::backtrace::imp::InternalBacktrace::new
   1: <error_chain::State as core::default::Default>::default
   2: jormungandr::blockchain::chain::Blockchain::post_check_header
   3: futures::future::chain::Chain<A,B,C>::poll
   4: futures::future::chain::Chain<A,B,C>::poll
   5: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
   6: <futures::future::map::Map<A,F> as futures::future::Future>::poll
   7: futures::task_impl::std::set
   8: std::thread::local::LocalKey<T>::with
   9: futures::future::Future::wait
  10: jormungandr::blockchain::process::run_handle_input
  11: jormungandr::blockchain::process::handle_input
  12: futures::future::catch_unwind::<impl futures::future::Future for std::panic::AssertUnwindSafe<F>>::poll
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  15: <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll
  16: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  17: futures::task_impl::std::set
  18: std::panicking::try::do_call
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  20: tokio_threadpool::task::Task::run
  21: tokio_threadpool::worker::Worker::run_task
  22: tokio_threadpool::worker::Worker::run
  23: std::thread::local::LocalKey<T>::with
  24: std::thread::local::LocalKey<T>::with
  25: std::thread::local::LocalKey<T>::with
  26: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  27: std::thread::local::LocalKey<T>::with
  28: std::thread::local::LocalKey<T>::with
  29: std::sys_common::backtrace::__rust_begin_short_backtrace
  30: std::panicking::try::do_call
  31: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  32: core::ops::function::FnOnce::call_once{{vtable.shim}}
  33: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  34: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  35: start_thread
  36: __clone
) } })', src/libcore/result.rs:1084:5
stack backtrace:
   0:     0x55930350f02b - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x55930350f02b - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x55930350f02b - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x55930350f02b - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x55930350f02b - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x55930350ed06 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x55930350f79d - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x55930350f322 - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x55930350f206 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x55930352c08d - core::panicking::panic_fmt::h7e9f94035af782b3
                               at src/libcore/panicking.rs:85
  10:     0x55930352c187 - core::result::unwrap_failed::hf7591c1dd9412006
                               at src/libcore/result.rs:1084
  11:     0x55930309099f - jormungandr::blockchain::process::run_handle_input::heaeb842bfda0817d
  12:     0x55930308bdea - jormungandr::blockchain::process::handle_input::h79cb277ff6138b8a
  13:     0x559302f8622b - futures::future::catch_unwind::<impl futures::future::Future for std::panic::AssertUnwindSafe<F>>::poll::hf463501d6d2c781f
  14:     0x559302bd383c - std::panicking::try::do_call::h8febcd1b74ac34eb
  15:     0x55930351377a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  16:     0x559302db05f6 - <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll::he121ebf08418841a
  17:     0x559302dac4e5 - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::hda03856537c5c49a
  18:     0x5593034ec082 - futures::task_impl::std::set::h19287d092715b0c6
  19:     0x5593034ebcb2 - std::panicking::try::do_call::h95eda1c6d1780785
  20:     0x55930351377a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  21:     0x5593034eb8d9 - tokio_threadpool::task::Task::run::h4390d3a630692d70
  22:     0x5593034e6556 - tokio_threadpool::worker::Worker::run_task::h69272c057f74a1be
  23:     0x5593034e59f0 - tokio_threadpool::worker::Worker::run::h12ae03ca77efb8aa
  24:     0x5593034c56b0 - std::thread::local::LocalKey<T>::with::h2e60e1c599c2492c
  25:     0x5593034c5d88 - std::thread::local::LocalKey<T>::with::h8326b5dcd39e66cf
  26:     0x5593034c5a9f - std::thread::local::LocalKey<T>::with::h4c63294a8f2719ac
  27:     0x5593034c969e - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h8c8fe1a41aecf62a
  28:     0x5593034e917a - std::thread::local::LocalKey<T>::with::hb16b02795dd0943a
  29:     0x5593034e8f69 - std::thread::local::LocalKey<T>::with::h9c883615db26fc1d
  30:     0x5593034e2cd8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4da395819657b52a
  31:     0x5593034ebcfc - std::panicking::try::do_call::ha774c1441d731aaf
  32:     0x55930351377a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  33:     0x5593034e3da0 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1d2eaa2374bbdff4
  34:     0x5593034fffff - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h2877b2aefb0fd627
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  35:     0x559303512ac0 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h13f473dbcdaa0fef
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  36:     0x559303512ac0 - std::sys_common::thread::start_thread::h562a7c4953cb1d31
                               at src/libstd/sys_common/thread.rs:13
  37:     0x559303512ac0 - std::sys::unix::thread::Thread::new::thread_start::h382c6ae14181d163
                               at src/libstd/sys/unix/thread.rs:79
  38:     0x7f9bf22e46db - start_thread
  39:     0x7f9bf1df588f - __clone
  40:                0x0 - <unknown>
called `Result::unwrap()` on an `Err` value: Error(Msg("cannot process leadership block"), State { next_error: Some(Error(BlockHeaderVerificationFailed("Invalid block message"), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0: error_chain::backtrace::imp::InternalBacktrace::new
   1: <error_chain::State as core::default::Default>::default
   2: jormungandr::blockchain::chain::Blockchain::post_check_header
   3: futures::future::chain::Chain<A,B,C>::poll
   4: futures::future::chain::Chain<A,B,C>::poll
   5: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
   6: <futures::future::map::Map<A,F> as futures::future::Future>::poll
   7: futures::task_impl::std::set
   8: std::thread::local::LocalKey<T>::with
   9: futures::future::Future::wait
  10: jormungandr::blockchain::process::run_handle_input
  11: jormungandr::blockchain::process::handle_input
  12: futures::future::catch_unwind::<impl futures::future::Future for std::panic::AssertUnwindSafe<F>>::poll
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  15: <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll
  16: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  17: futures::task_impl::std::set
  18: std::panicking::try::do_call
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  20: tokio_threadpool::task::Task::run
  21: tokio_threadpool::worker::Worker::run_task
  22: tokio_threadpool::worker::Worker::run
  23: std::thread::local::LocalKey<T>::with
  24: std::thread::local::LocalKey<T>::with
  25: std::thread::local::LocalKey<T>::with
  26: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  27: std::thread::local::LocalKey<T>::with
  28: std::thread::local::LocalKey<T>::with
  29: std::sys_common::backtrace::__rust_begin_short_backtrace
  30: std::panicking::try::do_call
  31: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  32: core::ops::function::FnOnce::call_once{{vtable.shim}}
  33: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  34: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  35: start_thread
  36: __clone
) } })), backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0: error_chain::backtrace::imp::InternalBacktrace::new
   1: <error_chain::State as core::default::Default>::default
   2: jormungandr::blockchain::chain::Blockchain::post_check_header
   3: futures::future::chain::Chain<A,B,C>::poll
   4: futures::future::chain::Chain<A,B,C>::poll
   5: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
   6: <futures::future::map::Map<A,F> as futures::future::Future>::poll
   7: futures::task_impl::std::set
   8: std::thread::local::LocalKey<T>::with
   9: futures::future::Future::wait
  10: jormungandr::blockchain::process::run_handle_input
  11: jormungandr::blockchain::process::handle_input
  12: futures::future::catch_unwind::<impl futures::future::Future for std::panic::AssertUnwindSafe<F>>::poll
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  15: <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll
  16: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  17: futures::task_impl::std::set
  18: std::panicking::try::do_call
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  20: tokio_threadpool::task::Task::run
  21: tokio_threadpool::worker::Worker::run_task
  22: tokio_threadpool::worker::Worker::run
  23: std::thread::local::LocalKey<T>::with
  24: std::thread::local::LocalKey<T>::with
  25: std::thread::local::LocalKey<T>::with
  26: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  27: std::thread::local::LocalKey<T>::with
  28: std::thread::local::LocalKey<T>::with
  29: std::sys_common::backtrace::__rust_begin_short_backtrace
  30: std::panicking::try::do_call
  31: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  32: core::ops::function::FnOnce::call_once{{vtable.shim}}
  33: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  34: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  35: start_thread
  36: __clone
) } })

**Comment by smurf123444** [comment] 2019-10-17 00:14
whats your node config look like

**Comment by NicolasDP** [comment] 2019-11-11 13:09
this issue was a duplicated #1065 (or #1065 was the duplicate of this one 🤔  ). this is now fixed.

**Closed by NicolasDP** 2019-11-11 13:09 UTC
