### ISSUE TITLE
node crashed shortly after upgrade 0.8.8

### ISSUE THREAD

**Issue by onicrom** [input-output-hk/jormungandr#1679] opened 2020-01-30 08:34 UTC
Was running 0.8.7 node had not been online for ~12 hours. Upgraded to 0.8.8 started node, it read in the chain history, then tried to download newer blocks was failing to connect to peers. I restarted the node and during bootstrap it crashed with the following:

```
Jan 30 03:10:41.899 INFO connecting to bootstrap peer 54.183.149.167:3000, peer_addr: 54.183.149.167:3000, task: bootstrap
thread 'tokio-runtime-worker-3' panicked at 'validated block must be unique', src/libcore/option.rs:1185:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'internal error: entered unreachable code', /home/cardano/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/mod.rs:296:26
```

**Comment by rinor** [comment] 2020-01-30 08:49
Duplicate of https://github.com/input-output-hk/jormungandr/issues/1677

**Closed by rinor** 2020-01-30 08:49 UTC
