### ISSUE TITLE
Node keeps on crashing 0.8.3 ITN

### ISSUE THREAD

**Issue by Gertjan-stakingpoolholder** [input-output-hk/jormungandr#1401] opened 2019-12-19 07:21 UTC
**Describe the bug**
The node crashes after about 30 minutes. Before it crashes WARN messages appear:

"Dec 19 08:05:37.843 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network"

After some time the node crashes with the following:
Dec 19 07:51:43.726 ERRO Error while accepting connection on 192.168.0.9:3100: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, task: network
Dec 19 07:51:43.733 INFO service finished with error, task: network
Dec 19 07:51:43.734 CRIT Service has terminated with an error

ulimit is set to 8192

**Mandatory Information**
1. `jcli --full-version` output : jcli 0.8.3
2. `jormungandr --full-version` output; jormungandr 0.8.3 (HEAD-8f276c0, release, macos [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**
Run the node

**Expected behavior**
I expect the node not to crash

**Additional context**
I also see sometimes "HTTP 2.0 connection error". I also see sometimes "failed to connect to peer, reason: Connection refused (os error 61)". I also see sometimes "peer node ID differs from the expected". I also see sometimes "failed to connect to peer, reason: Operation timed out (os error 60)"

**Comment by Gertjan-stakingpoolholder** [comment] 2019-12-19 09:37
Additional info: I also see this: Dec 19 10:35:59.487 ERRO cannot compute the time passed since the last block: second time provided was later than self, task: stuck_notifier

**Comment by Gertjan-stakingpoolholder** [comment] 2019-12-19 09:41
Addional info: I also see this: ec 19 10:41:02.256 ERRO cannot process network headers, reason: deadline has elapsed, task: block

**Comment by Gertjan-stakingpoolholder** [comment] 2019-12-19 09:42
It is the same pattern repeating. So messages like mentioned and then it crashes.

**Comment by CardanoUmbrella** [comment] 2019-12-19 14:07
I am also getting the same errors

**Comment by Gertjan-stakingpoolholder** [comment] 2019-12-19 15:41
The node will not last running mor than 20-30 minutes

**Comment by Gertjan-stakingpoolholder** [comment] 2019-12-19 16:21
My apologies. Full version icli : jcli 0.8.3 (HEAD-8f276c0, release, macos [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**Comment by Gertjan-stakingpoolholder** [comment] 2019-12-20 06:57
The node switched to another branch, which many times slower, however the node does not crash anymore. #1407

**Comment by mzabaluev** [comment] 2019-12-21 06:19
> I also see sometimes "HTTP 2.0 connection error". I also see sometimes "failed to connect to peer, reason: Connection refused (os error 61)". I also see sometimes "peer node ID differs from the expected". I also see sometimes "failed to connect to peer, reason: Operation timed out (os error 60)"

These messages are all caused by various problems with connecting to peers. It's expected that some peers would cause these, but we log the errors for troubleshooting.

**Comment by mzabaluev** [comment] 2019-12-21 06:32
The problem might be caused by this: https://github.com/joyent/illumos-joyent/issues/148

**Comment by Gertjan-stakingpoolholder** [comment] 2019-12-23 14:23
Issue with crashing node was gone with 0.8.5 alpha 3. Issue is back with 0.8.5

**Comment by mzabaluev** [comment] 2020-01-08 08:51
Duplicate of #1367

**Closed by mzabaluev** 2020-01-08 08:51 UTC
Labels: duplicate
