### ISSUE TITLE
not yet implemented: method to load a Ref from the storage is not yet there

### ISSUE THREAD

**Issue by Madmosa** [input-output-hk/jormungandr#1027] opened 2019-10-24 20:54 UTC
**Describe the bug**
jormungandr crashes after block announcment  with "thread 'block0' panicked at 'not yet implemented: method to load a Ref from the storage is not yet there', jormungandr/src/blockchain/chain.rs:259:37"

**Mandatory Information**
1. jcli 0.7.0-rc1 (HEAD-5583e5e, release, linux [arm]) - [rustc 1.38.0 (625451e37 2019-09-23)]
2. jcli 0.7.0-rc1 (HEAD-5583e5e, release, linux [arm]) - [rustc 1.38.0 (625451e37 2019-09-23)]

**To Reproduce**
1. Start jormungandr --> ./jormungandr --config ./node-config.yaml --genesis-block-hash ae57995b8fe086ba590c36dc930f2aa9b52b2ffa92c0698fff2347adafe8dc65 --log-level=info

**Additional context**
Oct 24 22:46:51.640 INFO received block announcement, hash: 63250b73e66ef3bcee9fada1b8b4286e355f4b54d17589700b4d5fd85754de2a, direction: in, stream: block_events, node_id: c92e9f50ea87d4e965f08057e53054eed306918b444334f6b3f463ccc2cc014b, sub_task: server, task: network
thread 'block0' panicked at 'not yet implemented: method to load a Ref from the storage is not yet there', jormungandr/src/blockchain/chain.rs:259:37
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:339
   9: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  10: <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll
  11: <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll
  12: <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll
  13: futures::task_impl::Spawn<T>::poll_future_notify
  14: jormungandr::blockchain::process::run_handle_input
  15: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
  16: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  17: futures::task_impl::std::set
  18: tokio_threadpool::worker::Worker::run_task
  19: tokio_threadpool::worker::Worker::run
  20: std::thread::local::LocalKey<T>::with
  21: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
not yet implemented: method to load a Ref from the storage is not yet there
thread

**Comment by NicolasDP** [comment] 2019-10-24 22:29
duplicate of #788

**Closed by NicolasDP** 2019-10-24 22:29 UTC
Labels: duplicate
