### ISSUE TITLE
Node using old parent hash for block creation

### ISSUE THREAD

**Issue by adascanBovich** [input-output-hk/jormungandr#1579] opened 2020-01-16 10:22 UTC
**Describe the bug**
My slot was scheduled at 33.26558, 33.26554 was received at 09:58:51 with parent hash f889f397fdb13175e7989cac7ca8c100ba7fb10367f7d1c259acb2189a6ddbdb. Then at 09:58:53 my node created scheduled block 33.26558, using the same parent - f889f397fdb13175e7989cac7ca8c100ba7fb10367f7d1c259acb2189a6ddbdb. As a reslut block was lost.

**Mandatory Information**
1. jcli 0.8.6 (HEAD-7686397, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2. jormungandr 0.8.6 (HEAD-7686397, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
1. Start a pool.
2. Check logs every time you are missing your blocks

**Expected behavior**
Node should've used new parent from 33.26554

**Additional context**
33.26554 - received:
<img width="714" alt="Screenshot 2020-01-16 at 12 08 13" src="https://user-images.githubusercontent.com/58727428/72516618-a2565380-385a-11ea-8392-e896a2c19092.png">

33.26558 created with the same parent:
<img width="714" alt="Screenshot 2020-01-16 at 12 01 58" src="https://user-images.githubusercontent.com/58727428/72516680-c6199980-385a-11ea-89f7-9d25b9dff787.png">

**Comment by rinor** [comment] 2020-01-16 11:07
@adascanBovich Thank you for the report. This case may be related the one being discussed at https://github.com/input-output-hk/jormungandr/issues/1513

**Comment by NicolasDP** [comment] 2020-01-17 19:50
I think this is duplicate of #1513

**Closed** 2020-01-17 19:52 UTC
Labels: duplicate
