### ISSUE TITLE
Node panicked - "cannot process leadership block" 0.7.0-rc7

### ISSUE THREAD

**Issue by feqifei** [input-output-hk/jormungandr#1107] opened 2019-11-11 05:17 UTC
**Describe the bug**
Node crashes processing leadership block. Not able to reproduce it, it happened twice always on the last assigned slot of an epoch.

**Mandatory Information**
1. `jcli --full-version` output;
jcli 0.7.0-rc7 (HEAD-cf5fcae, release, macos [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
2. `jormungandr --full-version` output;
jormungandr 0.7.0-rc7 (HEAD-cf5fcae, release, macos [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**
Not reproducible

**Additional context**
Nov 11 02:39:04.396 INFO block successfully applied, date: 16.7119, parent: 9741063499a1e609ee3a76337067cb9e12c0c8706c0611b903baf8adc9dfdce0, hash: e495cdaece16fbfc01aacde8c21d8f247ca55fc72c05afda0da665de1a7817c6, task: block
Nov 11 02:39:04.397 INFO update current branch tip, date: 16.7119, parent: 9741063499a1e609ee3a76337067cb9e12c0c8706c0611b903baf8adc9dfdce0, hash: e495cdaece16fbfc01aacde8c21d8f247ca55fc72c05afda0da665de1a7817c6, task: block
Nov 11 02:39:04.574 INFO leader event starting, date: 16.7119, leader: 1, task: leadership
thread 'block0' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Msg("cannot process leadership block"), State { next_error: Some(Error(CannotApplyBlock, State { next_error: Some(NonMonotonicDate { block_date: BlockDate { epoch: 16, slot_id: 7119 }, chain_date: BlockDate { epoch: 16, slot_id: 7119 } }), backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0: backtrace::capture::Backtrace::new_unresolved
   1: error_chain::backtrace::imp::InternalBacktrace::new
   2: error_chain::State::new
   3: jormungandr::blockchain::chain::Blockchain::apply_block
   4: <futures::future::map::Map<A,F> as futures::future::Future>::poll
   5: futures::task_impl::Spawn<T>::poll_future_notify
   6: jormungandr::blockchain::process::run_handle_input
   7: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
   8: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
   9: futures::task_impl::std::set
  10: tokio_threadpool::worker::Worker::run_task
  11: tokio_threadpool::worker::Worker::run
  12: std::thread::local::LocalKey<T>::with
  13: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  17: std::sys::unix::thread::Thread::new::thread_start
  18: _pthread_body
  19: _pthread_start
) } })), backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0: backtrace::capture::Backtrace::new_unresolved
   1: error_chain::backtrace::imp::InternalBacktrace::new
   2: error_chain::State::new
   3: jormungandr::blockchain::chain::Blockchain::apply_block
   4: <futures::future::map::Map<A,F> as futures::future::Future>::poll
   5: futures::task_impl::Spawn<T>::poll_future_notify
   6: jormungandr::blockchain::process::run_handle_input
   7: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
   8: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
   9: futures::task_impl::std::set
  10: tokio_threadpool::worker::Worker::run_task
  11: tokio_threadpool::worker::Worker::run
  12: std::thread::local::LocalKey<T>::with
  13: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  17: std::sys::unix::thread::Thread::new::thread_start
  18: _pthread_body
  19: _pthread_start
) } })', src/libcore/result.rs:1165:5
stack backtrace:
   0:        0x1081dad82 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h66f38d4abb2e41c1
   1:        0x107bbfb90 - core::fmt::write::h4f487e714088986d
   2:        0x1081da4cb - std::io::Write::write_fmt::h7bd7b6fe8b47c5fb
   3:        0x1081da125 - std::panicking::default_hook::{{closure}}::heee79636c241547c
   4:        0x1081d9633 - std::panicking::rust_panic_with_hook::h0c4b67125f55410a
   5:        0x1081de13e - std::panicking::continue_panic_fmt::h0e74ab2b215a1401
   6:        0x1081e8da9 - rust_begin_unwind
   7:        0x107bb9ed7 - core::panicking::panic_fmt::h09741a3213dba543
   8:        0x107bc0209 - core::result::unwrap_failed::hf47c31c429b02014
   9:        0x107d2a1da - jormungandr::blockchain::process::run_handle_input::hbec31585d078749c
  10:        0x107ed7c9c - <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll::hc0b02c7ee5160841
  11:        0x107cb4c04 - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h3dbaf5b809f2503f
  12:        0x10822c826 - futures::task_impl::std::set::haa4f2eb0ac996060
  13:        0x10822858d - tokio_threadpool::worker::Worker::run_task::h92391b3aa632ddce
  14:        0x1082267df - tokio_threadpool::worker::Worker::run::hebe7ce2b53de5162
  15:        0x10820c8f3 - std::thread::local::LocalKey<T>::with::h827f2c1984a91054
  16:        0x10820d771 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h8ac65d3859c75bf2
  17:        0x108224911 - std::sys_common::backtrace::__rust_begin_short_backtrace::hce34341927f76660
  18:        0x108225e24 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hacfedcce583f87bf
  19:        0x1081e7b5e - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hd1afe4d791e3679f
  20:        0x1081e9c9a - std::sys::unix::thread::Thread::new::thread_start::h785fcf8d81bd0f52
  21:     0x7fffa7df693b - _pthread_body
  22:     0x7fffa7df6887 - _pthread_start
called `Result::unwrap()` on an `Err` value: Error(Msg("cannot process leadership block"), State { next_error: Some(Error(CannotApplyBlock, State { next_error: Some(NonMonotonicDate { block_date: BlockDate { epoch: 16, slot_id: 7119 }, chain_date: BlockDate { epoch: 16, slot_id: 7119 } }), backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0: backtrace::capture::Backtrace::new_unresolved
   1: error_chain::backtrace::imp::InternalBacktrace::new
   2: error_chain::State::new
   3: jormungandr::blockchain::chain::Blockchain::apply_block
   4: <futures::future::map::Map<A,F> as futures::future::Future>::poll
   5: futures::task_impl::Spawn<T>::poll_future_notify
   6: jormungandr::blockchain::process::run_handle_input
   7: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
   8: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
   9: futures::task_impl::std::set
  10: tokio_threadpool::worker::Worker::run_task
  11: tokio_threadpool::worker::Worker::run
  12: std::thread::local::LocalKey<T>::with
  13: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  17: std::sys::unix::thread::Thread::new::thread_start
  18: _pthread_body
  19: _pthread_start
) } })), backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0: backtrace::capture::Backtrace::new_unresolved
   1: error_chain::backtrace::imp::InternalBacktrace::new
   2: error_chain::State::new
   3: jormungandr::blockchain::chain::Blockchain::apply_block
   4: <futures::future::map::Map<A,F> as futures::future::Future>::poll
   5: futures::task_impl::Spawn<T>::poll_future_notify
   6: jormungandr::blockchain::process::run_handle_input
   7: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
   8: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
   9: futures::task_impl::std::set
  10: tokio_threadpool::worker::Worker::run_task
  11: tokio_threadpool::worker::Worker::run
  12: std::thread::local::LocalKey<T>::with
  13: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  17: std::sys::unix::thread::Thread::new::thread_start
  18: _pthread_body
  19: _pthread_start
) } })
thread 'leadership0' panicked at 'Expect the event to not close',

**Comment by feqifei** [comment] 2019-11-11 05:19
[nohup.out.bck.zip](https://github.com/input-output-hk/jormungandr/files/3829805/nohup.out.bck.zip)

**Comment by rdlrt** [comment] 2019-11-11 05:36
Duplicate of #1024 / #1065

**Comment by NicolasDP** [comment] 2019-11-11 12:55
definitely a duplicate. Good news is that it is fixed on master 🎉

**Closed by NicolasDP** 2019-11-11 12:55 UTC
Labels: duplicate

**Comment by feqifei** [comment] 2019-11-11 14:44
ok, thanks
