### ISSUE TITLE
In mac getting error "blockchain is not moving up, the last block was 1830 seconds ago, task: stuck_notifier"

### ISSUE THREAD

**Issue by BitcoinMicroPaymentNetwork** [input-output-hk/jormungandr#1454] opened 2019-12-26 06:00 UTC
**Describe the bug**
In mac getting error "blockchain is not moving up, the last block was 1830 seconds ago, task: stuck_notifier" . After this the node stops syncing up with latest block. 

**Mandatory Information**
1. jcli 0.8.4 (HEAD-2227eb2, release, macos [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2. jormungandr 0.8.4 (HEAD-2227eb2, release, macos [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
It comes after running for 5 hours in mac 

**Expected behavior**
The node should be always in sync with latest block

**Comment by rinor** [comment] 2020-01-03 12:44
@BitcoinMicroPaymentNetwork `blockchain is not moving up` is a symptom and not the issue per se. While a notification that your node may be stuck and/or not synching anymore, it can be caused by different issues already reported and being tracked. Thanking you for the report, do you think you can close this one since a bit too generalistic and you are providing more details in another related issue https://github.com/input-output-hk/jormungandr/issues/1470. Thank you.

**Comment by BitcoinMicroPaymentNetwork** [comment] 2020-01-03 17:43
sure

**Closed** 2020-01-06 09:37 UTC
Labels: duplicate
