### ISSUE TITLE
Node crash with "free(): invalid next size (fast)"

### ISSUE THREAD

**Issue by jbgi** [input-output-hk/jormungandr#820] opened 2019-09-24 09:25 UTC
**Describe the bug**
Maybe related to #819.
Last logs of the node (r-c-2) before crash:
```
Sep 24 09:02:43.078 DEBG updating P2P local topology, task: network
Sep 24 09:02:43.078 DEBG sending gossip to node 13217782415942583296, task: network
Sep 24 09:02:43.078 INFO ignoring P2P node without an IP address: Node(Node { id: Id([0, 132, 169, 148, 19, 255, 110, 183]), address: None, subscriptions: Subscriptions({Topic(0): High, Topic(1): Low}), subscribers: {}, last_gossip: Syst>
Sep 24 09:02:43.078 DEBG selecting gossips for 3325764316396488704, task: network
Sep 24 09:02:43.393 DEBG sending gossip to node 3325764316396488704, task: network
Sep 24 09:02:43.393 INFO ignoring P2P node without an IP address: Node(Node { id: Id([0, 136, 123, 109, 6, 125, 39, 46]), address: None, subscriptions: Subscriptions({Topic(0): High, Topic(1): Low}), subscribers: {}, last_gossip: SystemT>
Sep 24 09:02:43.394 DEBG selecting gossips for 10003975837273789952, task: network
Sep 24 09:02:43.658 DEBG sending gossip to node 10003975837273789952, task: network
Sep 24 09:02:43.658 INFO ignoring P2P node without an IP address: Node(Node { id: Id([0, 150, 75, 74, 5, 67, 213, 138]), address: None, subscriptions: Subscriptions({Topic(0): High, Topic(1): Low}), subscribers: {}, last_gossip: SystemTi>
Sep 24 09:02:43.659 DEBG selecting gossips for 2566787167711764480, task: network
Sep 24 09:02:43.923 DEBG sending gossip to node 2566787167711764480, task: network
Sep 24 09:02:43.924 INFO ignoring P2P node without an IP address: Node(Node { id: Id([0, 160, 125, 97, 84, 15, 159, 35]), address: None, subscriptions: Subscriptions({Topic(1): Low, Topic(0): High}), subscribers: {}, last_gossip: SystemT>
Sep 24 09:02:43.925 DEBG selecting gossips for 5343397573359544576, task: network
Sep 24 09:02:44.010 DEBG received; frame=Data { stream_id: StreamId(3) }, scope: global
Sep 24 09:02:44.010 DEBG scheduling Read for: 9, scope: global
Sep 24 09:02:44.010 DEBG block is missing a locally stored parent, task: block
Sep 24 09:02:44.189 DEBG sending gossip to node 5343397573359544576, task: network
Sep 24 09:02:44.194 INFO ignoring P2P node without an IP address: Node(Node { id: Id([0, 169, 199, 77, 200, 143, 39, 74]), address: None, subscriptions: Subscriptions({Topic(0): High, Topic(1): Low}), subscribers: {}, last_gossip: System>
Sep 24 09:02:44.194 DEBG selecting gossips for 13476109815152227584, task: network
Sep 24 09:02:44.454 DEBG sending gossip to node 13476109815152227584, task: network
Sep 24 09:02:44.454 INFO ignoring P2P node without an IP address: Node(Node { id: Id([0, 181, 77, 54, 122, 194, 4, 187]), address: None, subscriptions: Subscriptions({Topic(0): High, Topic(1): Low}), subscribers: {}, last_gossip: SystemT>
Sep 24 09:02:44.455 DEBG selecting gossips for 6794770255639918336, task: network
Sep 24 09:02:44.717 DEBG sending gossip to node 6794770255639918336, task: network
Sep 24 09:02:44.717 INFO ignoring P2P node without an IP address: Node(Node { id: Id([0, 183, 206, 25, 140, 223, 75, 94]), address: None, subscriptions: Subscriptions({Topic(0): High, Topic(1): Low}), subscribers: {}, last_gossip: System>
Sep 24 09:02:44.718 DEBG selecting gossips for 9308127813561859328, task: network
Sep 24 09:02:44.981 DEBG sending gossip to node 9308127813561859328, task: network
Sep 24 09:02:44.981 INFO ignoring P2P node without an IP address: Node(Node { id: Id([0, 189, 73, 11, 238, 28, 45, 129]), address: None, subscriptions: Subscriptions({Topic(1): Low, Topic(0): High}), subscribers: {}, last_gossip: SystemT>
Sep 24 09:02:44.982 DEBG selecting gossips for 17333941650976069632, task: network
Sep 24 09:02:45.246 DEBG sending gossip to node 17333941650976069632, task: network
Sep 24 09:02:45.246 INFO ignoring P2P node without an IP address: Node(Node { id: Id([0, 216, 198, 167, 23, 136, 142, 240]), address: None, subscriptions: Subscriptions({Topic(0): High, Topic(1): Low}), subscribers: {}, last_gossip: Syst>
Sep 24 09:02:45.247 DEBG selecting gossips for 13907485447579165184, task: network
free(): invalid next size (fast)
/nix/store/0249dxdgfjp3hn1vkvashs2mm05mkzvq-unit-script-jormungandr-start: line 5: 10821 Aborted                 (core dumped) RUST_BACKTRACE=1 /nix/store/v49ggr37n0lg0qq9bwflwqhm546ifa7d-jormungandr-0.5.0/bin/jormungandr --genesis-block>
jormungandr.service: Main process exited, code=exited, status=134/n/a
```

**Mandatory Information**
1. `jcli --full-version` output;
jcli 0.5.0 (, release, linux [x86_64]) - [rustc 1.37.0 (eae3437df 2019-08-13)]
2. `jormungandr --full-version` output;
jormungandr 0.5.0 (, release, linux [x86_64]) - [rustc 1.37.0 (eae3437df 2019-08-13)]

**Comment by NicolasDP** [comment] 2019-09-25 09:10
I don't believe the `--full-version` returned you these values.

**Comment by jbgi** [comment] 2019-09-25 10:31
@NicolasDP right, fixed!

**Comment by mzabaluev** [comment] 2019-09-25 16:29
Likely duplicate of #814

**Closed by mzabaluev** 2019-09-25 16:29 UTC
Labels: Priority - High, bug, jörmungandr
