### ISSUE TITLE
CRIT Task panicked, task: block

### ISSUE THREAD

**Issue by Rugbertl** [input-output-hk/jormungandr#1408] opened 2019-12-19 20:56 UTC
**Describe the bug**
Several critical errors in the logs.

**Mandatory Information**
1. jcli 0.8.4 (HEAD-2227eb2, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2. jormungandr 0.8.4 (HEAD-2227eb2, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**Additional context**
Dec 19 21:02:51.460 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
thread 'block0' panicked at 'missed chain pull root candidate 057dd91fe904a850d8c8b2200ac1929c4ff1d6a3aa671c454ad2ceefb806a04a that got committed to storage', jormungandr/src/blockchain/candidate.rs:560:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Dec 19 21:02:57.852 CRIT Task panicked, task: block
Dec 19 21:02:57.852 WARN response canceled by the processing task, request: UploadBlocks, sub_task: server, task: network
thread 'block0' panicked at 'missed chain pull root candidate 057dd91fe904a850d8c8b2200ac1929c4ff1d6a3aa671c454ad2ceefb806a04a that got committed to storage', jormungandr/src/blockchain/candidate.rs:560:13
Dec 19 21:02:59.739 CRIT Task panicked, task: block
Dec 19 21:02:59.739 WARN response canceled by the processing task, request: UploadBlocks, sub_task: server, task: network
Dec 19 21:03:00.118 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
thread 'block0' panicked at 'missed chain pull root candidate 057dd91fe904a850d8c8b2200ac1929c4ff1d6a3aa671c454ad2ceefb806a04a that got committed to storage', jormungandr/src/blockchain/candidate.rs:560:13
Dec 19 21:03:00.606 CRIT Task panicked, task: block
Dec 19 21:03:00.607 WARN response canceled by the processing task, request: UploadBlocks, sub_task: server, task: network
Dec 19 21:03:01.982 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 19 21:03:16.774 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
thread 'block1' panicked at 'missed chain pull root candidate 057dd91fe904a850d8c8b2200ac1929c4ff1d6a3aa671c454ad2ceefb806a04a that got committed to storage', jormungandr/src/blockchain/candidate.rs:560:13
Dec 19 21:03:22.393 WARN response canceled by the processing task, request: UploadBlocks, sub_task: server, task: network
Dec 19 21:03:22.393 CRIT Task panicked, task: block
thread 'block1' panicked at 'missed chain pull root candidate 057dd91fe904a850d8c8b2200ac1929c4ff1d6a3aa671c454ad2ceefb806a04a that got committed to storage', jormungandr/src/blockchain/candidate.rs:560:13
Dec 19 21:03:27.769 CRIT Task panicked, task: block
Dec 19 21:03:27.770 WARN response canceled by the processing task, request: UploadBlocks, sub_task: server, task: network
Dec 19 21:03:51.206 ERRO cannot process network headers, reason: deadline has elapsed, task: block
Dec 19 21:03:51.312 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network

**Comment by laplasz** [comment] 2019-12-22 14:45
I think is the duplicate of #1388

**Comment by rinor** [comment] 2020-01-03 11:31
@Rugbertl while the mentioned issues are partialy fixed in v0.8.5, there are some more fixes to be merged in like https://github.com/input-output-hk/jormungandr/pull/1461. Furthermore the issues mentioned here are included in issue https://github.com/input-output-hk/jormungandr/issues/1422 which is being tracked and fixes are in work/ready. Can we close this one? Thank you.

**Closed** 2020-01-03 18:35 UTC
