### ISSUE TITLE
Network Thread Panic at Shutdown

### ISSUE THREAD

**Issue by arussell29** [input-output-hk/jormungandr#1466] opened 2019-12-28 03:20 UTC
**Describe the bug**
Jormungandr Node (v0.8.5) running on Ubuntu 18.04, 24 hours+ of uptime prior to this event.
I noticed blockHeight on node failed to increase for over an hour and so logged in via SSH to restart the node.
Issued a shutdown command via terminal and jcli, next viewed log and discovered panic and backtrace that seemed to occur at shutdown.
Jormungandr log also reported: "WARN blockchain is not moving up, the last block was 4380 seconds ago, task: stuck_notifier" prior to the panic.

log contents: (note that times shown are Eastern Standard)
Dec 27 04:17:32.782 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 27 04:17:36.467 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 27 04:17:40.302 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 27 04:17:43.534 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 27 04:17:50.494 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 27 04:17:51.281 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 27 04:17:51.989 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 27 04:17:52.388 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 27 04:17:55.827 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 27 04:17:57.267 WARN blockchain is not moving up, the last block was 4380 seconds ago, task: stuck_notifier
Dec 27 04:17:58.038 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
thread 'network1' panicked at 'called `Result::unwrap()` on an `Err` value: SpawnError { is_shutdown: true }', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: jormungandr::network::send_gossip
  16: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
  17: <futures::future::join::Join3<A,B,C> as futures::future::Future>::poll
  18: futures::future::chain::Chain<A,B,C>::poll
  19: futures::task_impl::std::set
  20: std::panicking::try::do_call
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  22: tokio_threadpool::task::Task::run
  23: tokio_threadpool::worker::Worker::run_task
  24: tokio_threadpool::worker::Worker::run
  25: tokio_reactor::with_default
  26: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  27: std::thread::local::LocalKey<T>::with
  28: std::thread::local::LocalKey<T>::with
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Dec 27 04:17:58.252 CRIT Task panicked, task: network

**Mandatory Information**
1. `jcli --full-version` output; jcli 0.8.5 (heads/v0.8.5-3db06807, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

2. `jormungandr --full-version` output; jormungandr 0.8.5 (heads/v0.8.5-3db06807, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
1. Run node as leader candidate.
2. Node blockHeight stops increasing and log reports stuck_notifier warning.
3. Issue command line shutdown request via jcli.

**Expected behavior**
A clean shutdown is expected with no panics or backtraces reported

**Additional context**
I log the blockHeights of my node and the ITN Shelley Explorer from a remote machine (i.e. not running on the node itself) that is updated approximately every two minutes. I am including here some information from the node monitoring app I had written to watch for problems with my node. I will attach a plot showing the moment at which the blockHeight on my node stopped moving up.
![Log7Plot2](https://user-images.githubusercontent.com/58673770/71538155-777c7d80-28f4-11ea-9366-19b17099688b.PNG)
I stopped the monitoring app at 4:12 AM EST, approximately 5 minutes prior to issuing the node shutdown command via SSH terminal. In the plot above the blue dots represent the blockHeight of my node and the orange dots are the simultaneous blockHeight reported by the ITN Shelley Explorer. I observe that node blockHeight stops advancing on 12/27/2019 at 2:26 AM EST. Following this moment at which my node begins to lag the explorer blockHeight, my node blockHeight increases twice more by one prior to my intervention to shutdown the node (from 44674 to 44675 at 2:46 AM and from 44675 to 44676 at 3:07 AM). Note that the information I copied from the Jormungandr log reported at 4:18 AM that the last block received had been 4380 seconds (or about 73 minutes) prior. 73 minutes prior to 4:18 AM is consistent with my monitoring data that showed the last block was received at about 3:07 AM (again, all times EST).

I can submit my monitoring data log if it becomes necessary. Please contact me if this or any additional information is required. I have tried to submit all relevant information in this report.

**Comment by arussell29** [comment] 2019-12-28 03:47
Just noticed that this issue is probably the same as #1444 already reported.

**Comment by kakerley** [comment] 2019-12-29 04:37
I am running ubuntu 18.04 on 8.5 also and have experienced this several times. I am also consistently getting the following:
c 29 03:56:42.092 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 29 03:56:42.584 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 29 03:56:43.050 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 29 03:56:43.645 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 29 03:57:29.266 WARN request timed out or failed unexpectedly, error: Error(Elapsed), request: GetHeadersRange, task: client-query
Dec 29 03:57:29.284 WARN request timed out or failed unexpectedly, error: Error(Elapsed), request: GetHeadersRange, task: client-query
Dec 29 03:57:39.118 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 29 03:57:39.628 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 29 03:57:40.383 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 29 03:57:40.443 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network

**Comment by NicolasDP** [comment] 2020-01-17 20:12
duplicate of #1444

**Closed by NicolasDP** 2020-01-17 20:12 UTC
