### ISSUE TITLE
Jormungandr v0.8.7 fails to bootstrap

### ISSUE THREAD

**Issue by A-Caccese** [input-output-hk/jormungandr#1635] opened 2020-01-23 21:41 UTC
**Describe the bug**
After the upgrade to Jorm. 8.7 I'm unable to bootstrap on Ubuntu 18.04. I tried to delete the storage and also to delisting the unreacheble trusted peers but nothing works. Reinstalled Jorm. 8.6, it works without problem. Tried to reinstall Jorm. 8.7 after 8 hours, but I had the same problem.

**Mandatory Information**
1. jcli 0.8.7 (linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2. jormungandr 0.8.7 (linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**Additional context**
Logs tail:
Jan 23 19:59:21.464 DEBG validated block, block_date: 41.788, hash: eacdf60c15eda399a898322450b0264c6037c3b08c12d2388cbf3cbb69b75171, peer_addr: 3.125.183.71:3000, task: bootstrap
Jan 23 19:59:21.471 INFO update current branch tip, peer_addr: 3.125.183.71:3000, task: bootstrap
Jan 23 19:59:21.475 DEBG validated block, block_date: 41.790, hash: e4072bf7ef6dca7c3e07ef800e3a12fb28106b0ff80f150d33f41803d2e06371, peer_addr: 3.125.183.71:3000, task: bootstrap
Jan 23 19:59:21.479 INFO update current branch tip, peer_addr: 3.125.183.71:3000, task: bootstrap
Jan 23 19:59:21.482 DEBG validated block, block_date: 41.814, hash: e177586e1c9b52d3caf31f445d1584744f5ec7d6b2646402cde0da9a0f3ef102, peer_addr: 3.125.183.71:3000, task: bootstrap
Jan 23 19:59:21.486 INFO update current branch tip, peer_addr: 3.125.183.71:3000, task: bootstrap
Jan 23 19:59:21.491 DEBG validated block, block_date: 41.832, hash: 929a6d313ac8cc95cb07b1c061f36a554e4888d819ccf68788c6a22bdc9808a0, peer_addr: 3.125.183.71:3000, task: bootstrap
Jan 23 19:59:21.494 INFO update current branch tip, peer_addr: 3.125.183.71:3000, task: bootstrap
Jan 23 19:59:21.497 INFO initial bootstrap completed, peer_addr: 3.125.183.71:3000, task: bootstrap
Jan 23 19:59:21.542 INFO listening and accepting gRPC connections, local_addr: 0.0.0.0:3100, task: network

**Comment by mzabaluev** [comment] 2020-01-23 22:09
The log shows bootstrap is complete. How does the failure manifest itself?

**Comment by A-Caccese** [comment] 2020-01-23 23:45
The node seemed to bootstrap, but "jcli rest v0 node stats get -h http://127.0.0.1:${REST_PORT}/api" didn't show neither "lastBlockTime" or "lastReceivedBlockTime". Moreover the log gets stuck on "INFO listening and accepting gRPC connections, local_addr: 0.0.0.0:3100, task: network".

**Comment by stakehodlers** [comment] 2020-01-24 00:49
Had a similar experience, but slightly different.  When I shutdown 0.8.6; replaced the executables with 0.8.7, and started the node, the node stats command returned "Bootstrapping" for over 2 hours.  I got sick of waiting for it and rebooted the HW.  The node then bootstrapped properly and has been running with an uptime of ~60k since.  I've seen long boot times in the past, but with the first boot of 0.8.7 it was exceptionally long.  Not sure if it would have completed had I left it alone.

**Comment by rinor** [comment] 2020-01-26 17:38
Duplicate of https://github.com/input-output-hk/jormungandr/issues/1637

**Closed** 2020-01-30 17:26 UTC
Labels: duplicate, question
