### ISSUE TITLE
Extreme Return on Staking Possible Bug?!

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/jormungandr#1517] opened 2020-01-07 13:35 UTC
Reported via Zendesk: https://iohk.zendesk.com/agent/tickets/80487

Chris:
I have observed a possible bug in the Daedalus Incentivized Testnet Rewards Wallet,
I staked a very small sum of tADA to two trusted pools, I left it delegated to the pools for a few days and then moved both sums to another person's Daedalus Incentivized Testnet Rewards Wallet, I was unable to move every Lovelace out of the two Wallets I used to send to this other person so each wallet continued to delegate 1 Lovelace each to the pools I chose initially, The rewards for 1 Lovelace on the first day was 96 Lovelace in one pool and 172 in the other,I have included my logs for you to inspect to see if this is a bigger problem or just a small glitch I have observed, I will also try to replicate the issue with larger amounts of tADA left in reward wallets that will be delegated to the same pools as when I first discovered the little bug, please let me know if you have any questions.

**Comment by carl-IOHK** [comment] 2020-01-07 13:57
Problem createde https://iohk.myjetbrains.com/youtrack/issue/IOHKS-183

**Comment by NicolasDP** [comment] 2020-01-08 09:20
From what you are saying, what happens is the following:

| epoch K | delegate to some pools |
| epoch K+1 | empty all stake from the pool |
| epoch K+1 | still receiving reward on the account |
| epoch K+2 | still receiving reward on the account |

is that what is being reported?

**Comment by NicolasDP** [comment] 2020-01-08 09:22
And please, don't share links that are not public here. they will be deleted as no one can access them.

**Comment by carl-IOHK** [comment] 2020-01-08 09:26
Nicolas before you delete the link to the ticket, please let us know how are we supposed to link this issue to the item in Zendesk?

**Comment by carl-IOHK** [comment] 2020-01-08 09:29
Nicolas, how should we link this issue to the issue in Zendesk? Reported via Zendesk: https://iohk.zendesk.com/agent/tickets/80487 is also not a public link.

**Comment by NicolasDP** [comment] 2020-01-08 09:31
@carl-IOHK I meant the youtrack issue you have added in the second comment. The zendesk issue is good enough thanks and it is already in the issue description.

**Comment by carl-IOHK** [comment] 2020-01-08 09:35
OK we can get to the Youtrack issue via the Zendesk issue it's just less
direct. I will inform the team that you only want Zendesk links in the
Jormungandr Repo.

**Comment by Haskell-plus** [comment] 2020-01-08 21:26
Gentlemen,
On Jan-2-2020 just minutes into Epoch 20 is when I transferred out of my rewards wallets that have the issue, I report today that the rewards balance continues to grow just as it did when I discovered this issue with just 1 Lovelace delegated in each wallet.

**Comment by NicolasDP** [comment] 2020-01-17 20:15
I have tried to reproduce this issue. are you using this with Daedalus or Yoroi?

**Comment by rdlrt** [comment] 2020-01-18 01:19
@NicolasDP - I had a chat with user on telegram, while he moved out funds, there was already rewards earned worth ~0.7ADA - the (usable) balance of wallet on the otherhand was few 1 lovelace. Thus, the reward he was earning was correct when considering entire wallet balance.

**Comment by Haskell-plus** [comment] 2020-01-21 02:40
@NicolasDP This Question can be closed as @rdlrt described there were rewards in the wallet before leaving just 1 lovelace left remaining - The automatic redelegation of rewards caused the confusion I was using Daedalus, sorry if I have wasted your time but thanx for looking into it anyway  :)

**Comment by NicolasDP** [comment] 2020-01-21 09:50
Thanks everyone. Good work finding the root cause of all of this.

**Closed by NicolasDP** 2020-01-21 09:50 UTC
Labels: question
