### ISSUE TITLE
API service to start before initial network bootstrap and before loading storage

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/jormungandr#970] opened 2019-10-16 21:15 UTC
**Is your feature request related to a problem/context ? Please describe if applicable.**
API service only starts after initial network bootstrap

**Describe the solution you'd like**
API service to start before initial network bootstrap and before loading storage

**Additional context**
Needed for orchestration of node, wallet backed and daedalus
Also eliminates on class of user error when using CLI

**Comment by rdlrt** [comment] 2019-10-16 22:13
Duplicate of #857 ?

**Closed** 2019-10-17 08:30 UTC
Labels: duplicate
