### ISSUE TITLE
error[E0277]: the trait bound `cid::Error: std::error::Error` is not satisfied

### ISSUE THREAD

**Issue by A-Caccese** [input-output-hk/jormungandr#1891] opened 2020-03-08 22:02 UTC
**Describe the bug**
Hi, I'm having E0277 when compiling `multiaddr v0.3.1` on Ubuntu 18.04.4 LTS.

**To Reproduce**
`cargo install --path jormungandr --force`

**Comment by rinor** [comment] 2020-03-08 22:28
@A-Caccese  try `cargo install --path jormungandr --force --locked`

**Comment by A-Caccese** [comment] 2020-03-09 08:50
> @A-Caccese try `cargo install --path jormungandr --force --locked`

Done, I had the same error.

**Comment by NicolasDP** [comment] 2020-03-09 08:54
duplicate of #1879

**Closed** 2020-03-09 08:54 UTC
Labels: duplicate
