### ISSUE TITLE
/api/v0/account/{account_id}  truncating address resulting in 404 not found

### ISSUE THREAD

**Issue by sedwardstx** [input-output-hk/jormungandr#908] opened 2019-10-08 04:38 UTC
**Describe the bug**
Rest api for "account get" appears to truncate 1st character of address, then fails with 404

**Mandatory Information**
1. `jcli --full-version` output;
PS C:\node> .\jcli.exe --full-version
jcli 0.5.6 (HEAD-7ab929ea+, release, windows [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

2. `jormungandr --full-version` output;
PS C:\node> .\jormungandr.exe --full-version
jormungandr 0.5.6 (HEAD-7ab929ea+, release, windows [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

**To Reproduce**

.\jcli.exe rest v0 account get ca1skshe434wclgkxw9405tqu9y6fpztcryuwg0g4nuetl800rvz4q45j67249 --host "http://127.0.0.1:3101/api
failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://127.0.0.1:3101/api/v0/account/a17cd635763e8b19c5abe8b070a4d24225e064e390f4567ccafe77bc6c15415a: Client Error: 404 Not Found

**Expected behavior**
expect the url should be
http://127.0.0.1:3101/api/v0/account/ca17cd635763e8b19c5abe8b070a4d24225e064e390f4567ccafe77bc6c15415a

**Additional context**

**Comment by rdlrt** [comment] 2019-10-08 05:40
Please use shelley-testnet repo for reporting any issues/enhancements. Duplicate of input-output-hk/shelley-testnet#92

**Comment by CodeSandwich** [comment] 2019-10-10 23:32
@sedwardstx I've "fixed" it, but after a second thought I'm not sure if that's really an issue.

This JCLI command accepts two formats of account ID: address and public key. Address is a public key with single byte added on the beginning, which marks what the public key should be used for (in your case it says it's account for testing).

The REST API accepts only one format: public key. When JCLI gets public key, it's sent as whole, but if it gets address, it strips the first byte to turn it into a raw public key. You're observing exactly that. Hex representation of your address starts with `85a17c...`, but only `a17c...` is sent, which is correct behavior. If you pass into JCLI address with first byte stripped, which makes it a raw a public key, it'll be sent as a whole resulting in the same request being made. Check it out: `ca1597dvdtk8693n3dtazc8pfxjggj7qe8rjr69vlx2lemmcmq4g9dqf7kcee`.

I'm not sure why are you getting a 404, @rdlrt's link could be a clue.

**Closed** 2019-10-11 07:38 UTC
