### ISSUE TITLE
Error downloading initial bootstrap from official trusted peers

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#843] opened 2019-09-27 06:36 UTC
**Describe the bug**
Multiple error log messages can be seen when starting the node - the reason seems that there is an error getting initial bootstrap from provided/official trusted peers.

**Mandatory Information**
```
jcli 0.5.2 (HEAD-e7a3efe7, release, windows [x86_64]) - [rustc 1.37.0 (eae3437df 2019-08-13)]
jormungandr 0.5.2 (HEAD-e7a3efe7, release, windows [x86_64]) - [rustc 1.37.0 (eae3437df 2019-08-13)]
```

**To Reproduce**
1. start a local node with provided trusted peers --> `jormungandr ---config node_config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770`

**Expected behavior**
No errors should be seen, at least regarding the connections to the official trusted peers.

**Additional context**
- os: win10
- node has direct connection with outside/internet
- node config:
```
rest:
  listen: "127.0.0.1:9000"
p2p:
  public_address: /ip4/5.12.xx.xx/tcp/3000
  listen_address: /ip4/192.168.xx.xx/tcp/3000
  trusted_peers: [/ip4/3.123.177.192/tcp/3000,
                  /ip4/3.123.155.47/tcp/3000,
                  /ip4/52.57.157.167/tcp/3000,
                  /ip4/3.112.185.217/tcp/3000,
                  /ip4/18.140.134.230/tcp/3000,
                  /ip4/18.139.40.4/tcp/3000,
                  /ip4/3.115.57.216/tcp/3000]
  topics_of_interest:
    messages: high
    blocks: high
```
- node logs:
[node_logs.txt](https://github.com/input-output-hk/jormungandr/files/3661183/node_logs.txt)
![image](https://user-images.githubusercontent.com/29144964/65747366-f30a3b00-e109-11e9-9980-0fbea565202c.png)

**Comment by mzabaluev** [comment] 2019-09-27 07:31
Right, we still log errors from all peer connect attempts at error level, though bootstrap eventually succeeds. Need to improve the logging.

**Comment by dorin100** [comment] 2019-09-27 07:33
My main concern here is that the provided-peers are generating those errors... My expectation would be that we provide `functional` / `working` trusted peers (I suppose this is why they are `trusted`..)

**Comment by mzabaluev** [comment] 2019-09-27 10:18
> My main concern here is that the provided-peers are generating those errors...

Yes, that's to be fixed on the trusted peer nodes, and the causes for request failures need to be investigated there. Right now the trusted nodes are overloaded because we got our p2p topology to always try to connect to these nodes, which is not really necessary. We will try to tweak this. Please file issues with logs from the trusted nodes detailing the failures on that side that cause requests to fail.

As far as the bootstrapping node is concerned, the warning log messages should be an appropriate way to signal intermittent failures as long as bootstrap eventually completes successfully. Previously, a failure to reach the one peer was fatal because no attempts were made to try with the other peers, hence use of `error!` for failures in bootstrapping.

**Closed** 2019-09-27 10:36 UTC
Labels: subsys-network
