### ISSUE TITLE
Node panicked - Os { code: 1455, kind: Other, message: "The paging file is too small for this operation to complete." }

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#967] opened 2019-10-16 14:05 UTC
**Describe the bug**
Node panicked after ~7 hours

**Mandatory Information**
1. used version `0.6.1` from release files (OS: windows VM)
```
jormungandr 0.6.1 (HEAD-a0de8d47, release, windows [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
jcli 0.6.1 (HEAD-a0de8d47, release, windows [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
```

**To Reproduce**
1. Start the node as a leader and let it run

**Expected behavior**
The node should not crash

**Additional context**
- stack trace
```
Oct 16 13:34:47.593 INFO incoming P2P connection closed, peer_addr: 96.248.209.37:63183, task: network
thread 'network0' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1455, kind: Other, message: "The paging file is too small for this operation to complete." }', src\libcore\result.rs:1084:5
stack backtrace:
   0:           0x7d2d93 - <unknown>
   1:           0x7d1f9a - <unknown>
   2:           0x7d8442 - <unknown>
   3:           0x7e4949 - <unknown>
   4:           0x7ef88c - <unknown>
   5:           0x7f5e1f - <unknown>
   6:           0x4713ac - <unknown>
   7:           0x97db67 - <unknown>
   8:           0x92d6a2 - <unknown>
   9:           0x8422a3 - <unknown>
  10:           0x7b6c5c - <unknown>
  11:           0x7ba4c3 - <unknown>
  12:           0x7b8628 - <unknown>
  13:           0x79c236 - <unknown>
  14:           0x79fa31 - <unknown>
  15:           0x7b61c4 - <unknown>
  16:           0x7b7072 - <unknown>
  17:           0x7e3e86 - <unknown>
  18:           0x7e548c - <unknown>
  19:     0x7ff965a537e4 - <unknown>
  20:     0x7ff96850cb81 - <unknown>
called `Result::unwrap()` on an `Err` value: Os { code: 1455, kind: Other, message: "The paging file is too small for this operation to complete." }
Oct 16 13:34:51.781 ERRO Error accepting connection: Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093), scope: global
```
- node logs:
[node_log.txt](https://github.com/input-output-hk/jormungandr/files/3734720/node_log.txt)

**Comment by mzabaluev** [comment] 2019-10-19 13:11
Looks like an out of memory problem, possible duplicate of #956.

**Closed** 2020-06-09 06:50 UTC
