### ISSUE TITLE
Error while accepting connection on 0.0.0.0:3000

### ISSUE THREAD

**Issue by BitcoinMicroPaymentNetwork** [input-output-hk/jormungandr#1458] opened 2019-12-26 13:58 UTC
**Describe the bug**

Dec 26 19:14:14.551 ERRO Error while accepting connection on 0.0.0.0:3000: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, task: network
Dec 26 19:14:14.561 WARN response canceled by the processing task, request: UploadBlocks, sub_task: server, task: network
Dec 26 19:14:14.568 CRIT Service has terminated with an error

**Mandatory Information**
It is happening on version 8.5 on Mac OS Mojave

**To Reproduce**
Run the node and it happens some times

**Comment by eugene-babichenko** [comment] 2019-12-27 16:40
Duplicate of #1401

**Comment by lsc3** [comment] 2020-01-05 19:51
FWIW ...I have same issue with v0.8.5, Mac OS Mojave.

**Closed** 2020-01-08 08:49 UTC
Labels: duplicate
