### ISSUE TITLE
Node crashed network thread 'block2' panicked at 'internal error: entered unreachable code'

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/jormungandr#919] opened 2019-10-10 20:48 UTC
https://github.com/input-output-hk/shelley-testnet/issues/113

**Comment by mzabaluev** [comment] 2019-10-11 05:43
The cause is this error: "unable to open database file", likely caused by exceeding the number of open file descriptors.

**Comment by mzabaluev** [comment] 2019-10-22 07:38
Duplicate of #923

**Closed** 2019-10-22 07:49 UTC
Labels: bug, duplicate, subsys-storage
