### ISSUE TITLE
0.8 rc4 - network hung after block validation failure + panic during bootstrapping

### ISSUE THREAD

**Issue by hodlonaut** [input-output-hk/jormungandr#1254] opened 2019-12-02 22:56 UTC
Running version jormungandr 0.8.0-rc4 (master-b1aa3c09+, release, macos [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)], private testnet.

Node was left running overnight, everything was running smoothly till just before 4.58am local time when received block announcement failed header verification:

```
Dec 03 04:58:40.197 INFO received block announcement, hash: 58b21fdb61a8a5f5d907b9f3a73a776f29bba5ed71339b640850a2c6246e3227, direction: in, stream: block_events, node_id: 15c0b4583630c9423addd5e08160422d6bced6da7766f87c, peer_addr: 100.21.146.169:8003, task: network
Dec 03 04:58:40.357 INFO validation of an incoming block failed, reason: The block header verification failed: Block proof is invalid, task: block
```

after this point in time, no more new blocks have been successfully applied on my node. The 'validation of an incoming block failed' message appeared 550 more times over the next 20 minutes, then stopped.

Subsequently, attempts to bootstrap from one of a few different trusted nodes all yielded a panic during bootstrapping phase:

```
Dec 03 09:44:31.166 DEBG validated block, block_date: 17.173, hash: ea950b4fa1260b802c7c2b73ad5c5c006eea91284e6bd0ecd3a4a12c150e0ad6, peer_addr: 185.161.193.61:9031, task: bootstrap
new_epoch_leadership_from - parent_date.epoch 17, epoch is 17
Dec 03 09:44:31.237 WARN initial bootstrap failed, error: HeaderCheckFailed { source: Error(BlockHeaderVerificationFailed("Block proof is invalid"), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new_unresolved
   2: error_chain::backtrace::imp::InternalBacktrace::new
   3: <error_chain::State as core::default::Default>::default
   4: jormungandr::blockchain::chain::Blockchain::post_check_header
   5: futures::future::chain::Chain<A,B,C>::poll
   6: futures::future::chain::Chain<A,B,C>::poll
   7: <futures::stream::fold::Fold<S,F,Fut,T> as futures::future::Future>::poll
   8: futures::future::chain::Chain<A,B,C>::poll
   9: futures::future::chain::Chain<A,B,C>::poll
  10: futures::future::chain::Chain<A,B,C>::poll
  11: futures::future::chain::Chain<A,B,C>::poll
  12: futures::task_impl::std::set
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
  15: tokio_threadpool::task::Task::run
  16: tokio_threadpool::worker::Worker::run_task
  17: tokio_threadpool::worker::Worker::run
  18: tokio_reactor::with_default
  19: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  20: std::thread::local::LocalKey<T>::with
  21: std::thread::local::LocalKey<T>::with
  22: std::sys_common::backtrace::__rust_begin_short_backtrace
  23: std::panicking::try::do_call
  24: __rust_maybe_catch_panic
  25: core::ops::function::FnOnce::call_once{{vtable.shim}}
  26: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  27: std::sys::unix::thread::Thread::new::thread_start
  28: _pthread_body
  29: _pthread_start
) } }) }, peer_addr: 185.161.193.61:9031, task: bootstrap
```

node is not operational after startup, a quick look at sqlite DB reveals 1791 entries in block and blockinfo tables, presumably the last entry is the one tripping over the bootstrapping (and presumably that's the block that failed verification on my node back when the hanging of the network started - but somehow at least one other node has persisted it in their blockchain DB?) 

The evidence to suggest that is that at least one trusted node (Markus) has a log record indicating that it successfully applied block for epoch.slot 17.182 while the bootstrap panic is related to:

Dec 03 09:19:06.792 TRCE received block from the bootstrap node: Header {
    version: 2,
    content_size: 0,
    date: BlockDate {
        epoch: 17,
        slot_id: 182,
    }

**Comment by hodlonaut** [comment] 2019-12-03 02:15
It looks like the header validation failure might have been specific/localized to my node and my local code change to delegator reward payments. However I suppose the question remains as to why entire network ended up in such a state as a result of such check failing (and presumably this can happen if node A has updated to newer jormungandr or is on older binaries and the rest of the network is on slightly different version)

**Comment by NicolasDP** [comment] 2019-12-09 18:20
the issue as to why the network has been in such a state has been addressed now. making it a duplicate of #1273

**Closed by NicolasDP** 2019-12-09 18:20 UTC
